POST http://localhost:3000/register/
Content-Type: application/json

{
    "username": "jayanth",
    "password": "ve43",
    "name": "Veena",
    "gender": "Female"
}
###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "veena",
    "password": "veena@143"
}

###
GET http://localhost:3000/users/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlZW5hIiwiaWF0IjoxNjc3MTI5ODc2fQ.4bs9YN2CbDe5ihlJAEU70AvT16W-XzrgACV97Vv-NEA
###


GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlZW5hIiwiaWF0IjoxNjc3MTI5ODc2fQ.4bs9YN2CbDe5ihlJAEU70AvT16W-XzrgACV97Vv-NEA

###
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlZW5hIiwiaWF0IjoxNjc3MTI5ODc2fQ.4bs9YN2CbDe5ihlJAEU70AvT16W-XzrgACV97Vv-NEA
###
GET http://localhost:3000/tweets/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlZW5hIiwiaWF0IjoxNjc3MTI5ODc2fQ.4bs9YN2CbDe5ihlJAEU70AvT16W-XzrgACV97Vv-NEA
###